version: '2'
services:
    atividade3-app:
        image: atividade3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://atividade3-mysql:3306/atividade3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    atividade3-mysql:
        extends:
            file: mysql.yml
            service: atividade3-mysql
